dataset:
  path: data
  train_batch_size: 128
  valid_batch_size: 1
model:
  embed_dim: 200
  encoder_hidden_dim: 200
  decoder_hidden_dim: 200
  encoder_heads: 4
  decoder_heads: 4
  encoder_layers: 1
  decoder_layers: 1
training:
  lr: 0.003
  epochs: 35
  model_name: model_v10-20-2024@14:22:41.pth
eval:
  rouge_vars:
  - L
  - 4
  - 3
  - 2
  - 1